### ISSUE TITLE
[retail] Add EACH

### ISSUE THREAD

**Issue by ptahchiev** [unitsofmeasurement/uom-domain#14]
Add EACH unit (can also be named PIECE). Also add BOX and a CRATE:
```
Quantity<Product> numberOfProducts = Quantities.getQuantity(20, EACH);
Quantity<Product> numberOfProducts = Quantities.getQuantity(20, BOX);
Quantity<Product> numberOfProducts = Quantities.getQuantity(20, CRATE);
```

**Comment by keilw** [comment]
Thanks, would you have a PR for that?

**Comment by keilw** [comment]
Hi,

I know, this has been around for some time, so not sure, how demand is, but in the absense of a PR I finalized some of those quantities myself.
```
Quantity<Box> box1 = Quantities.getQuantity(1, SMALL_BOX);
Quantity<Box> box2 = Quantities.getQuantity(2, BIG_BOX);
Quantity<Each<Box>> eachBoxes = Quantities.getQuantity(1, EACH_BOX);

Quantity<Crate> crate1 = Quantities.getQuantity(1, DOZEN);
Quantity<Crate> crate2 = Quantities.getQuantity(2, SIXPACK);
Quantity<Each<Crate>> eachCrates = Quantities.getQuantity(1, EACH_CRATE);
```

Not 100% sure about the `Each` type, it's currently modeled after the SI quantity meta-type [Level](https://github.com/unitsofmeasurement/si-units/blob/master/quantity/src/main/java/si/uom/quantity/Level.java), allowing a `Level` of another `Quantity`. 

@ptahchiev If you can, please check it out and tell us what you think.
I plan to release 2.1 soon, but any changes that do not make it there could be handled with a 2.2 version built on MR2 of the JSR.
