### ISSUE TITLE
Refactor the Indriya based MP-Metrics module to tech TLD

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-domain#5]
Although the Indriya based MP-Metrics module is going to use Indriya 1.0 for now, the package makes no sense under the old TLD, so it might as well start using the Java package name tech.uom right from the start.

Needs #3

**Comment by Daniel-Dos** [comment]
Hi @keilw ,

here is only change the package of `"tec.uom.domain.cloud.microprofile.metrics"` to `"tech.uom.domain.cloud.microprofile.metrics"`  ?

**Comment by keilw** [comment]
Yes, there may also be a new MP version as that keeps changing almost too fast (for potential users ;-)

**Comment by Daniel-Dos** [comment]
I to go close this issue.
